"""Added quiztemp db

Revision ID: 37c3caaa58d3
Revises: 9a37839336b7
Create Date: 2022-02-08 17:35:25.189934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c3caaa58d3'
down_revision = '9a37839336b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiztemp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('qn_id_str', sa.String(length=200), nullable=True),
    sa.Column('answer_str', sa.String(length=500), nullable=True),
    sa.Column('response_str', sa.String(length=500), nullable=True),
    sa.Column('next_qn_id', sa.Integer(), nullable=True),
    sa.Column('quiz_taker_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiztemp')
    # ### end Alembic commands ###
