"""Added Feedback temp db

Revision ID: c7804fd8cf3c
Revises: 203607735dc8
Create Date: 2022-02-10 17:43:49.378752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7804fd8cf3c'
down_revision = '203607735dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacktemp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fb_qn_str', sa.String(length=500), nullable=True),
    sa.Column('fb_response_str', sa.String(length=500), nullable=True),
    sa.Column('fb_qn_id', sa.Integer(), nullable=True),
    sa.Column('feedback_taker_id', sa.Integer(), nullable=True),
    sa.Column('date_given', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacktemp')
    # ### end Alembic commands ###
