"""Modified questions table

Revision ID: e007d103ea7b
Revises: c7804fd8cf3c
Create Date: 2022-02-11 18:44:46.877178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e007d103ea7b'
down_revision = 'c7804fd8cf3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('question_category', sa.String(length=30), nullable=False),
    sa.Column('choice1', sa.String(length=150), nullable=True),
    sa.Column('choice2', sa.String(length=150), nullable=True),
    sa.Column('choice3', sa.String(length=150), nullable=True),
    sa.Column('choice4', sa.String(length=150), nullable=True),
    sa.Column('choice5', sa.String(length=150), nullable=True),
    sa.Column('image1', sa.String(length=150), nullable=True),
    sa.Column('image2', sa.String(length=150), nullable=True),
    sa.Column('image3', sa.String(length=150), nullable=True),
    sa.Column('image4', sa.String(length=150), nullable=True),
    sa.Column('image5', sa.String(length=150), nullable=True),
    sa.Column('answer', sa.String(length=20), nullable=False),
    sa.Column('other_answer1', sa.String(length=250), nullable=True),
    sa.Column('other_answer2', sa.String(length=250), nullable=True),
    sa.Column('active_flag', sa.String(length=10), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('qn_creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['qn_creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_details', sa.String(length=900), nullable=False),
    sa.Column('date_taken', sa.DateTime(), nullable=True),
    sa.Column('quiz_taker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_taker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quizlogs')
    op.drop_table('questions')
    # ### end Alembic commands ###
