"""Added qn_type_str to quiztemp table

Revision ID: fbf7caff416e
Revises: e007d103ea7b
Create Date: 2022-02-12 17:49:53.058680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf7caff416e'
down_revision = 'e007d103ea7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiztemp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qn_id_str', sa.String(length=200), nullable=True),
    sa.Column('answer_str', sa.String(length=500), nullable=True),
    sa.Column('response_str', sa.String(length=500), nullable=True),
    sa.Column('qn_type_str', sa.String(length=500), nullable=True),
    sa.Column('next_qn_id', sa.Integer(), nullable=True),
    sa.Column('quiz_taker_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiztemp')
    # ### end Alembic commands ###
